# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My Course / Book Title
author: Moritz Rasched
logo: ASC_Logo_transparent_300ppi_RGB.png        # optional, add your own logo file
copyright: "2025"

execute:
  execute_notebooks: "auto"
  timeout: 300

repository:
  url: https://github.com/MoRasched/MoRasched.github.io

html:
  use_issues_button: false
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - amsmath
    - linkify
    - colon_fence
  myst_dmath_double_inline: true